---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  TelegramChannelScrapperFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: TelegramChannelScrapper
      Runtime: python3.9
      Handler: app.lambda_handler
      MemorySize: 128
      Timeout: 30
      Role: arn:aws:iam::530373754456:role/call-lambda-role
      CodeUri: telegram_channel_scrapper/app.py
